spring:
    application:
        name: api
    jpa:
        hibernate:
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/vollmed_api
        username: root
        password: root

server:
    error:
        whitelabel:
            enabled: false
        include-stacktrace: never

api:
    security:
        token:
            secret: ${JWT_SECRET:12345678}
    timezone:
        utc: +01:00